version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Build started on $(date)"
      - ls -l # Check the presence of index.html
      - sudo mkdir -p /var/www/html
      - sudo cp Repo-1/index.html /var/www/html

  post_build:
    commands:
      - echo "Configuring NGINX"
      - sudo nginx -g 'daemon off;' & # Start NGINX in the foreground as a background process
      - sleep 5 # Wait for NGINX to start
      - curl http://localhost # Verify the page is served correctly

artifacts:
  files:
    - /var/www/html/index.html
