version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Build started on $(date)"
      - ls -l # Check the presence of index.html
      - sudo mkdir -p /var/www/html
      - sudo cp index.html /var/www/html

  post_build:
    commands:
      - echo "Configuring NGINX"
      - sudo systemctl start nginx
      - curl http://localhost # Verify the page is served correctly

artifacts:
  files:
    - /var/www/html/index.html
